FROM node:22.9.0-alpine

WORKDIR /app

# Instala dependências
COPY package.json package-lock.json ./
RUN npm install

# Copia o código do frontend
COPY . .

# Expõe a porta do Vite
EXPOSE 5173

# Comando padrão
CMD ["npm", "run", "dev"]